# Generated by Django 4.2.2 on 2023-06-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inova_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='name',
            field=models.CharField(choices=[('Loyalty #1', 'Loyalty #1'), ('Loyalty #2', 'Loyalty #2'), ('Loyalty #3', 'Loyalty #3')], max_length=100),
        ),
    ]
